project:
  type: website
  render:
    - "*.qmd"
    - "*.Rmd"
    - "*.md"
    - "!README.md"
    - "!LICENSE.md"
    - "!myresources/"
    - "!certificate*"
  resources:
    - "static/"
    - "static/presentations/"

execute: 
  freeze: true

description-meta: "Personal homepage for Zane Billings"

website:
  title: "W. Zane Billings"
  navbar:
    right:
      - text: "home"
        href: index.qmd
      - text: "blog"
        href: blog.qmd
      # - text: "projects"
      #   href: projects.qmd
      # - text: "presentations"
      #   href: presentations.qmd
      # - text: "uses"
      #   href: uses.qmd
      # - text: "now"
      #   href: now.qmd
      # - text: "misc"
      #   href: misc.qmd
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/wzbillings/quarto-website/
        rel: me
  cookie-consent: true    
  search: true
  site-url: "https://wzbillings.com"
  repo-url: "https://github.com/wzbillings/quarto-website"
  draft-mode: gone
  
  page-footer:
    left: |
      {{< fa regular copyright >}} Zane Billings, 2023<br>
      All content licensed under {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-sa >}} {{< fa brands creative-commons-nc >}} [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [Source at {{< fa brands github >}} GitHub](https://github.com/wzbillings/quarto-website)

format:
  html:
    theme:
      light: pulse
      dark: vapor
    css: styles.css

metadata-files: 
  - drafts.yml



